# Generated by Django 3.2.12 on 2022-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_banner_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
